### ISSUE TITLE
Health Endpoint for Kubernetes

### ISSUE THREAD

**Issue by raynigon** [raynigon/github_billing_exporter#1]
Provide Health Endpoint for Kubernetes
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-billing-exporter
  labels:
    app.kubernetes.io/name: github-billing-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: github-billing-exporter
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: github-billing-exporter
    spec:
      serviceAccountName: default
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: exporter
          env:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: "github-secret-name"
                  key: "token"
          image: "raynigon/github-billing-exporter:v0.3.0"
          imagePullPolicy: IfNotPresent
          command:
            [
              "github_billing_exporter",
              "--log.format=logfmt",
              "--log.level=info",
              "--web.listen-address=:9776",
              "--web.telemetry-path=/metrics",
            ]
          securityContext:
            capabilities:
              drop:
                - SETPCAP
                - MKNOD
                - AUDIT_WRITE
                - CHOWN
                - NET_RAW
                - DAC_OVERRIDE
                - FOWNER
                - FSETID
                - KILL
                - SETGID
                - SETUID
                - NET_BIND_SERVICE
                - SYS_CHROOT
                - SETFCAP
            readOnlyRootFilesystem: true
          resources: {}
          ports:
            - containerPort: 9776
              name: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 1
            timeoutSeconds: 5
            periodSeconds: 5
          lifecycle:
            preStop:
              exec:
                command: ["/bin/bash", "-c", "sleep 20"]
          volumeMounts:
      volumes:

```
